export enum ActionType {
  // Game info related
  ADD_ENTRANCE_LINKS,
  UPDATE_INVENTORY,

  // Usb2Snes server related
  UPDATE_DEVICE_LIST,
  UPDATE_CONNECTED_DEVICE,
  UPDATE_SERVER_CONNECTION_STATUS,
  RESET_DEVICE_DATA,

  // Other
  UPDATE_APP_SETTINGS
}
